<?php
/**
 * @file
 * Enhanced control over the dates of any Block.
 *
 * Block dates allows users to add dates to any block through the block's
 * configuration interface. This implementation is based on date settings stored
 * in seperate table called 'block_by_date'
 */
/*
 * Defining Block from date value.
 */
define('BLOCK_FROM_DATE_DEFAULT_INIT', NULL);
/*
 * Defining Block to date value.
 */
define('BLOCK_TO_DATE_DEFAULT_INIT', NULL);
/**
 * Implements hook_permission().
 */
function block_by_date_permission() {
  return array(
    'administer block dates' => array(
      'title' => t('Administer block dates'),
      'description' => t('Set date limit for blocks.'),
    ),
  );
}

/**
 * Implements hook_form_alter(&$form, &$form_state, $form_id).
 * 
 */
function block_by_date_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('administer block dates') && ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form')) {

    // Load statically cached block object used to display the form.
    $block = block_load($form['module']['#value'], $form['delta']['#value']);

    // Adding date fieldset to the block configure page.
    $form['visibility']['dates_between'] = array(
      '#type' => 'fieldset',
      '#title' => 'Date & Time',
      '#weight' => 30,
      '#collapsible' => TRUE,
      '#group' => ' visibility',
      '#attached' => array(
        'js' => array(drupal_get_path('module', 'block_by_date') . '/js/block_by_date.js'),
      ),
     );
    $form['visibility']['dates_between']['from_date'] = array(
      '#type' => module_exists('date_popup') ? 'date_popup' : 'date_select' ,
      '#title' => t('From Date'), 
      '#date_format' => 'Y-m-d H:i',
      '#date_year_range' => '-3:+3',
      '#default_value' => isset($block->from_date) ? $block->from_date : variable_get('block_refresh_default_automatic_from_date', BLOCK_FROM_DATE_DEFAULT_INIT),
      '#description' => t('If you specify only from date, the block will be visible on that date onwards.'),
     );
    $form['visibility']['dates_between']['enable_end_date'] = array(
      '#type' => 'checkbox',
      '#title' => t('Collect an End Date'),
      '#ajax' => array(
      'wrapper' => 'end_date_wrapper',
      'callback' => 'block_by_date_form_ajax_callback',
      'method' => 'replace',
      'effect' => 'fade',
      ),
      '#default_value' => isset($block->to_date) ? 1 : 0,
      '#description' => t('E.g., Allow this block to appear on September 15, and end on September 16.'),
     );
    $form['visibility']['dates_between']['end_date_wrapper'] = array(
      '#prefix' => '<div id="end_date_wrapper">',
      '#suffix' => '</div>',
     );
    if ((!empty($block->to_date) && !isset($form_state['values']['enable_end_date'])) || (isset($form_state['values']['enable_end_date']) && (empty($block->to_date) && $form_state['values']['enable_end_date'] == 1) || (!empty($block->to_date) && $form_state['values']['enable_end_date'] == 1))) {
      $form['visibility']['dates_between']['end_date_wrapper']['to_date'] = array(
         '#type' => module_exists('date_popup') ? 'date_popup' : 'date_select', 
         '#title' => 'To Date',
         '#date_format' => 'Y-m-d H:i', 
         '#date_year_range' => '-3:+3',
         '#default_value' => isset($block->to_date) ? $block->to_date : variable_get('block_refresh_default_automatic_from_date', BLOCK_TO_DATE_DEFAULT_INIT),
         '#required' => TRUE,
        );        
    
    }
    // Add validation handler
    $form['#validate'][] = 'block_by_date_alter_validate_settings';
    $form['#submit'][] = 'block_by_date_form_submit';
  }
}

/**
 * Ajax callback. Returns To date filed if enable collect end date checkbox.
 *
 * @see block_by_date_form_alter()
 *
 */
function block_by_date_form_ajax_callback($form, &$form_state) {
  return $form['visibility']['dates_between']['end_date_wrapper'];
}

/**
 * Validation callback. Validates date settings per block.
 *
 * @see block_by_date_form_alter()
 * @see block_by_date_alter_save_settings()
 */
function block_by_date_alter_validate_settings($form, &$form_state) {
  $from_date = '';
  $to_date = '';
  if (isset($form_state['values']['from_date'])) {
    $from_date = $form_state['values']['from_date'];
  }
  if (isset($form_state['values']['to_date'])) {
    $to_date = $form_state['values']['to_date'];
  }
  if ($form_state['values']['module'] == 'block') {
    if (!empty($to_date) && (strtotime($from_date) > strtotime($to_date))) {
      form_set_error('dates_between', t('Ensure that from date is always less than to date.'));
    }
    elseif (!empty($from_date) && !empty($to_date) && (strtotime($from_date) == strtotime($to_date))) {
      form_set_error('dates_between', t('from and to date-time values should not equal'));
    }
  }
}

/**
 * Submit callback. Saves date settings per block.
 *
 * @see block_by_date_form_alter()
 *
 */
function block_by_date_form_submit($form, &$form_state) {
  if ($form_state['values']['form_id'] == 'block_admin_configure' || $form_state['values']['form_id'] == 'block_add_block_form') {
    
    $dates = array();
    if ($form_state['values']['from_date'] != '') {
      $dates['from_date'] = $form_state['values']['from_date'];
    }
    else {
      $dates['from_date'] = NULL;
    }
    if ($form_state['values']['enable_end_date'] == 1) {
      $dates['to_date'] = $form_state['values']['to_date'];
    }
    else {
      $dates['to_date'] = NULL;
    }
    $dates['check_todate'] = $form_state['values']['enable_end_date'];
    db_update('block')
        ->fields($dates)
        ->condition('module', $form_state['values']['module'])
        ->condition('delta', $form_state['values']['delta'])
        ->execute();
  }
}

/**
 * Implements hook_block_list_alter().
 *
 * Checks the date visibility settings.
 * Removes the block if the visibility conditions are not met.
 */
function block_by_date_block_list_alter(&$blocks) {
  foreach ($blocks as $key => $block) {
    $current_date = date('Y-m-d H:i');
    $default_value_from = $block->from_date;
    $default_value_to = $block->to_date;
    
    if (!empty($default_value_from) && !empty($default_value_to)) {
      if ((strtotime($current_date) >= strtotime($default_value_from)) && (strtotime($current_date) <= strtotime($default_value_to))) {
        // Nothing. Block will be visible.
      }
      else {
        // Disabling block.
         unset($blocks[$key]);
      }
    }
    elseif (!empty($default_value_from) && empty($default_value_to)) {
      if (strtotime($current_date) >= strtotime($default_value_from)) {
        // Nothing. Block will be visible.
      }
      else {
        // Disabling block.
         unset($blocks[$key]);
      }
    }
  }
}
